import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar configuration.
 *
 * Using the `type: 'autogenerated'` directive, Docusaurus walks the `docs/`
 * directory and builds the navigation tree from `_category_.json` files +
 * frontmatter `sidebar_position`. Drop a new `.md` file in and it shows up
 * automatically — no manual edits required.
 *
 * The five top-level categories mirror the directory layout:
 *   docs/getting-started   → 快速开始
 *   docs/constructure      → 项目结构介绍
 *   docs/guide             → 功能使用指南
 *   docs/api              → 接口说明
 *   docs/faq             → 常见问题
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
